Table users {
  id BIGINT [pk]
  full_name VARCHAR(30)
  email VARCHAR(100)
  password VARCHAR(60)
  phone VARCHAR(20)
  profile_image_url VARCHAR(250)
  created_at DATETIME2
  updated_at DATETIME2
}

Table roles {
  id BIGINT [pk]
  name VARCHAR(25)
  description VARCHAR(200)
}

Table user_roles {
  user_id BIGINT [ref: > users.id]
  role_id BIGINT [ref: > roles.id]
}

Table books {
  id BIGINT [pk]
  title VARCHAR(100)
  description VARCHAR(500)
  isbn VARCHAR(20)
  cover_url VARCHAR(250)
  file_url VARCHAR(250)
  published_year INT
  available BIT
  created_at DATETIME2
  updated_at DATETIME2
}

Table authors {
  id BIGINT [pk]
  full_name VARCHAR(50)
  biography VARCHAR(500)
  birth_date DATE
  created_at DATETIME2
}

Table categories {
  id BIGINT [pk]
  name VARCHAR(50)
  description VARCHAR(500)
  created_at DATETIME2
}

Table book_authors {
  book_id BIGINT [ref: > books.id]
  author_id BIGINT [ref: > authors.id]
}

Table book_categories {
  book_id BIGINT [ref: > books.id]
  category_id BIGINT [ref: > categories.id]
}

Table loans {
  id BIGINT [pk]
  user_id BIGINT [ref: > users.id]
  book_id BIGINT [ref: > books.id]
  loan_date DATETIME2
  return_date DATETIME2
  status VARCHAR(50)  [note: 'activo, devuelto, pendiente']
  created_at DATETIME2
}

Table reviews {
  id BIGINT [pk]
  user_id BIGINT [ref: > users.id]
  book_id BIGINT [ref: > books.id]
  rating INT
  comment VARCHAR(500)
  created_at DATETIME2
}