@startuml MER_Biblioteca

hide circle
skinparam linetype ortho

entity users {

  * id : BIGINT <<PK>>
  full_name : VARCHAR(100)
  email : VARCHAR(100)
  password : VARCHAR(255)
  phone : VARCHAR(20)
  profile_image_url : VARCHAR(255)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity roles {

  * id : BIGINT <<PK>>
  name : VARCHAR(100)
  description : VARCHAR(255)
}

entity user_roles {

  * user_id : BIGINT <<FK>>
  * role_id : BIGINT <<FK>>
}

entity books {

  * id : BIGINT <<PK>>
  title: VARCHAR(100)
  description : TEXT
  isbn : VARCHAR(13)
  cover_url : VARCHAR(255)
  file_url : VARCHAR(255)
  published_year : INT
  available : BOOLEAN
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity authors {

  * id : BIGINT <<PK>>
  full_name : VARCHAR(100)
  biography : TEXT
  birth_date : DATE
  created_at : TIMESTAMP
}

entity categories {

  * id : BIGINT <<PK>>
  name : VARCHAR(100)
  description : TEXT
  created_at : TIMESTAMP
}

entity book_authors {

  * book_id : BIGINT <<FK>>
  * author_id : BIGINT <<FK>>
}

entity book_categories {

  * book_id : BIGINT <<FK>>
  * category_id : BIGINT <<FK>>
}

entity loans {

  * id : BIGINT <<PK>>
  user_id : BIGINT <<FK>>
  book_id : BIGINT <<FK>>
  loan_date : TIMESTAMP
  return_date : TIMESTAMP
  status : VARCHAR(50)
  created_at : TIMESTAMP
}

entity reviews {

  * id : BIGINT <<PK>>
  user_id : BIGINT <<FK>>
  book_id : BIGINT <<FK>>
  rating : INT
  comment : TEXT
  created_at : TIMESTAMP
}

users ||--o{ loans
books ||--o{ loans

users ||--o{ reviews
books ||--o{ reviews

users ||--o{ user_roles
roles ||--o{ user_roles

books ||--o{ book_authors
authors ||--o{ book_authors

books ||--o{ book_categories
categories ||--o{ book_categories

@enduml