spring.application.name=library_management

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MER_Biblioteca;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=Password123*

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml